# -*- coding: utf-8 -*-
"""blackjack

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cJakrJQxfGCufghLh6MIq1pcFdQ0zEmG
"""

import random
from src.core.casino import player, admin

import random

class blackjack:
    def __init__(self):
        self.player = player()
        self.admin = admin()

        run = False
        while not run:
            userID = input("Enter your player ID: ")
            pword = input("Enter your password: ")

            if self.player.checkLogin(userID, pword):
                run = True
                self.uid = userID
            else:
                print("Login invalid, please try again")

        while run:
            userInput = input("Would you like to play (y/n): ")

            if userInput == 'y':
                self.admin.addWinnings(self.uid, -100)
                money = self.playGame()
                self.admin.addWinnings(self.uid, money)
                self.admin.addGame('Slots', self.uid, money)
                print(f"You earned: {money}, your balance is now {self.player.getWinnings(self.uid)}")
            else:
                quit()

  def playGame():
    playerbet = 100
    playerinput = ''
    cards = ['2','3','4','5','6','7','8','9','10','Jack','Queen','King','Ace']
    values = [2,3,4,5,6,7,8,9,10,10,10,10,11]
    suites = ['Hearts', 'Clubs', 'Diamonds', 'Spades']
    playerpoints = 0 
    dealerpoints = 0

    playercard1 = [ random.randint(0, 12) , random.randint(0,3) ]
    playercard2 = [ random.randint(0, 12) , random.randint(0,3) ] 

    dealercard1 = [ random.randint(0, 12) , random.randint(0,3) ]
    dealercard2 = [ random.randint(0, 12) , random.randint(0,3) ] 

    print('You have a ' + str(cards[playercard1[0]]) + ' of ' + str(suites[playercard1[1]]))
    print('and a ' + str(cards[playercard2[0]]) + ' of ' + str(suites[playercard2[1]]))
    print('Dealer\'s face card is a ' + str(cards[dealercard1[0]]) + ' of ' + str(suites[dealercard1[1]]))
    

    playerpoints += values[playercard1[0]] + values[playercard2[0]]
    if (values[playercard1[0]] == 11 and values[playercard2[0]] == 11):
      playerpoints -= 10
    playerinput = input('Add aditional card? q to stop')
    while (playerinput != 'q' and playerpoints <= 21):
      tablecard1 = [ random.randint(0, 12) , random.randint(0,3) ]
      print('You got a ' + str(cards[tablecard1[0]]) + ' of ' + str(suites[tablecard1[1]]))
      if (values[tablecard1[0]] == 11) :
        playerpoints += int(input('You got an ace, use it as a (1) or (11)?'))
      else :
        playerpoints += values[tablecard1[0]]
      if (playerpoints > 21):
        print('Player has over 21')
        break
      else :
        print('Player has ' + str(playerpoints) + ' points')
      playerinput = input('Add aditional card? q to stop')
    
    
    dealerpoints += values[dealercard1[0]] + values[dealercard2[0]]
    if (values[dealercard1[0]] == 11 and values[dealercard2[0]] == 11):
      dealerpoints -= 10
    while (dealerpoints < 17) :
      tablecard1 = [ random.randint(0, 12) , random.randint(0,3) ]
      print('Dealer got a ' + str(cards[tablecard1[0]]) + ' of ' + str(suites[tablecard1[1]]))
      dealerpoints += values[tablecard1[0]]
      if (values[tablecard1[0]] == 11 and dealerpoints > 21) :
        dealerpoints -= 10
      if (dealerpoints > 21):
        print('Dealer has over 21 and busts')
        break

    if (playerpoints > dealerpoints and playerpoints < 22) :
      print('Player wins!')
      return 5000
    elif (dealerpoints > playerpoints and dealerpoints < 22) : 
      print('Dealer wins!')
      return 0
    else  :
      print('It\'s a tie!')
      return 100

if __name__ == '__main__':
    blackjack()